### PR TITLE
Sync with skiboot, incorporate build fixes

### PR DESCRIPTION
**Pull request by ghost**
Big things here are being more flexible with C language definitions
(because of *ancient* C compilers used to build host binaries in
some systems), moving container.c to container-utils.c

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by hellerda** [comment]
Reviewing..

**Comment by hellerda** [comment]
I can see you want to enforce the rather old ANSI C standard of requiring all variable declarations at the start of the function.  Is this really necessary?  Would we ever hit a compliler that still doesn't understand this?

I had the impression that declaring vars close to the point of initialization is not only acceptable today but is in fact best practice, to reduce the scope of vars as much as possible, and to avoid any possibility a variable may be accessed uninitialized (or at least, quash such warnings from the many static analyzers we use).

To make my (current) code fail I need to add `std=c90 -Wpedantic` to my compiler flags, or explicitly tell it `-Wdeclaration-after-statement`.  I see the latter is present in the skiboot "Makefile.main", and I do remember hitting this when I looked at this code under skiboot.

Is that the reason for the restriction?  That this code must compiler under skiboot, and skiboot currently enforces this?

**Comment by ghost** [comment]
hellerda <notifications@github.com> writes:
> I can see you want to enforce the rather old ANSI C standard of
> requiring all variable declarations at the start of the function.  Is
> this really necessary?  Would we ever hit a compliler that still
> doesn't understand this?

RHEL6 ships with gcc 4.4 or something ancient, this is what's used on a
bunch of the pool machines inside IBM still, although that's probably
not as big issue as the -Wdeclaration-after-statement warning we enable.

> I had the impression that declaring vars close to the point of
> initialization is not only acceptable today but is in fact best
> practice, to reduce the scope of vars as much as possible, and to
> avoid any possibility a variable may be accessed uninitialized (or at
> least, quash such warnings from the many static analyzers we use).

yeah, generally speaking.

> To make my (current) code fail I need to add `std=c90 -Wpedantic` to
> my compiler flags, or explicitly tell it
> `-Wdeclaration-after-statement`.  I see the latter is present in the
> skiboot "Makefile.main", and I do remember hitting this when I looked
> at this code under skiboot.

> Is that the reason for the restriction?  That this code must compiler
> under skiboot, and skiboot currently enforces this?

-Wdeclaration-after-statement was added way back in the initial skiboot
commit in 2012 - it's been there since the very first git-init run.

It's to match linux kernel coding style, which we pretty much 100%
share and as such I don't want to disable the warning for the whole
tree. I *could* look at doing so just for host utilities though?

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by hellerda** [comment]
Sorry, I didn't see the tail end of your message in my viewer, else I would have replied yesterday.

Yes, if you are able to make the change, now would a fine time. :- )  I guess you'd have to remove  `-Wdeclaration-after-statement` from Makefile.main and move it to lower level Makefiles as appropriate.

I was prepared to merge this and add `-Wdeclaration-after-statement` to my own makefile going forward.  But if we can avoid it, I'd rather not.  Your call.  Thx -Dave

**Comment by hellerda** [comment]
Following some recent commits, this patch no longer applies.  But I'm just waiting on a ruling whether we need to enforce `-Wdeclaration-after-statement` going forward, and I can make the necessary adjustments.  Thx -Dave

**Comment by ghost** [comment]
hellerda <notifications@github.com> writes:
> Following some recent commits, this patch no longer applies.  But I'm
> just waiting on a ruling whether we need to enforce
> `-Wdeclaration-after-statement` going forward, and I can make the
> necessary adjustments.  Thx -Dave

(sorry for the delay getting back to this, you can probably guess all
the holdups :)

I'd like to, simply because it'd make the upsteram code match what we
build it with in skiboot (without doing custom cflags for it).... but I
can also tweak the makefiles in skiboot.

I'll take your call on this as you're the one maintaining this code and
will have to look at it a lot more than I will.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by hellerda** [comment]
I'm going to go ahead and close this, if that's OK.  We can reopen if we want to proceed.

**Pull request closed without merging**
